---

- name: screencapture is configured
  when: macos_screencapture_path
  macos_defaults:
    domain: com.apple.screencapture
    key: location
    state: present
    value: "{{ macos_screencapture_path }}" #"{{ ansible_env.HOME }}/Downloads"
  notify:
  - macos_restart_systemuiserver

- name: screencapture is de-configured
  when: not macos_screencapture_path
  macos_defaults:
    domain: com.apple.screencapture
    state: absent
  notify:
  - macos_restart_systemuiserver

# REF: http://stackoverflow.com/a/2119076
# DOES NOT WORK
#- name: wallpaper is set
#  command: defaults write com.apple.desktop Background '{default = {ImageFilePath = "~/wallpaper.jpg"; };}'

- name: dock size is configured
  when: macos_dock_size
  macos_defaults:
    domain: com.apple.dock
    key: tilesize
    state: present
    value: "{{ macos_dock_size }}"
  notify:
  - macos_restart_dock

- name: QuickLook animations are disabled
  when: not macos_animations
  macos_defaults:
    domain: -g
    key: QLPanelAnimationDuration
    state: present
    value: 0.0

- name: windows animations are disabled
  when: not macos_animations
  macos_defaults:
    domain: -g
    key: NSAutomaticWindowAnimationsEnabled
    state: present
    value: no
